/* ================= STATE & CONFIGURATION ================= */
let currentUser = null;
let pendingRegVerification = null;
let supabaseClient = null;
const SUPABASE_URL = "https://mmespmwztkxjhwmsgjn.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tZXNwbXd6dHhranhod21zZ2puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc5MzY5MzgsImV4cCI6MjEwMzUxMjkzOH0.wz8lllymLmmleherQwR2oqcYQbtXz8P_VqUU8xVhxE4";

const _savedLayout = localStorage.getItem('bs_feed_layout') || 'instagram';
const _isDesktopInit = typeof window !== 'undefined' && window.innerWidth >= 1024;
let selectedCategory = 'all', currentPage = 1, itemsPerPage = _savedLayout === 'list' ? (_isDesktopInit ? 18 : 10) : (_savedLayout === 'grid' ? (_isDesktopInit ? 24 : 12) : (_isDesktopInit ? 16 : 8)), favorites = [];
let adminAdsTab = 'active', LAST_NAV = 'home', searchQuery = '';
let currentSortMode = localStorage.getItem('bs_sort_mode') || 'newest';
let createMap = null, createMarker = null, detailMap = null, shopCreateMap = null, shopCreateMarker = null, showcaseMap = null;
let pendingCreateImages = [], pendingEditImages = [];
let cardPhotoIndex = {}, currentDetailPhotoIndex = 0;
let shopEditTargetUid = null, onBehalfPreset = null;
let editingCatId = null, catNameDraft = '', catIconChoice = 'fa-mobile-screen';
let comboBuilderAds = [], comboSelectedIds = [], comboOwnerCache = null;
let lastRatesUpdate = null, sharePayload = null, modalStack = [];
let reports = [];
let lastReportCount = 0;
let lastShareBlob = null;
let lastShareObjectUrl = null;
let hasCloudMarqueeSettings = false;
let MARQUEE_SETTINGS = { text: '', color: '#a8a8a8', fontSize: 13, speed: 20, direction: 'left', pauseOnHover: false };
let BACKUPS_META = {};
try {
  const savedBackups = localStorage.getItem('bs_backups_meta');
  if (savedBackups) BACKUPS_META = JSON.parse(savedBackups);
} catch(e) {}

let AVITOCASH_PRICES = { adPrice: 1, shopSubscription: 5, editPrice: 0, freeAdsCount: 0 };
let AVITOCASH_RATE = 1;
let TOPUP_REQUESTS = {};
try {
  const savedReqs = localStorage.getItem('bs_topup_requests');
  if (savedReqs) TOPUP_REQUESTS = JSON.parse(savedReqs);
} catch(e) {}
let GIFT_CODES = {};
let TRANSACTIONS = {};
const MARQUEE_STORAGE_KEY = 'bs_marquee_text';
const AVITOCASH_ID = '3adfe36abcbe52f1a4b008cd324082fb';
const PLACEHOLDER_IMG = 'https://placehold.co/800x1000/1e293b/fff?text=Avito+Türk';
let EXCHANGE_RATES = { TRY: 38.50 };
let SYSTEM_CONFIG = { rulesAccepted: false, adminTab: 'overview' };
const REGION_NAMES = { 
  'IST': 'İstanbul', 'ANK': 'Ankara', 'IZM': 'İzmir', 'BUR': 'Bursa', 
  'ANT': 'Antalya', 'GAZ': 'Gaziantep', 'HAT': 'Hatay', 'MER': 'Mersin', 
  'URF': 'Şanlıurfa', 'KON': 'Konya', 'ADA': 'Adana', 'KAY': 'Kayseri', 
  'SAM': 'Samsun', 'TRA': 'Trabzon' 
};
const REGION_COORDS = { 
  'IST': [41.0082, 28.9784], 'ANK': [39.9334, 32.8597], 'IZM': [38.4192, 27.1287], 
  'BUR': [40.1885, 29.0610], 'ANT': [36.8969, 30.7133], 'GAZ': [37.0662, 37.3833], 
  'HAT': [36.2023, 36.1606], 'MER': [36.8121, 34.6415], 'URF': [37.1674, 38.7955], 
  'KON': [37.8746, 32.4932], 'ADA': [36.9914, 35.3308], 'KAY': [38.7205, 35.4826], 
  'SAM': [41.2867, 36.3300], 'TRA': [41.0027, 39.7168] 
};
let categories = [
  { id:'electronics', name:'Elektronik', icon:'fa-laptop' },
  { id:'transport', name:'Vasıta & Araçlar', icon:'fa-car' },
  { id:'realestate', name:'Emlak', icon:'fa-house' },
  { id:'tools', name:'Alet & Edavat', icon:'fa-hammer' },
  { id:'home', name:'Ev & Yaşam', icon:'fa-couch' },
  { id:'food', name:'Gıda & Market', icon:'fa-utensils' },
  { id:'fashion', name:'Giyim & Moda', icon:'fa-shirt' },
  { id:'services', name:'Hizmetler', icon:'fa-wrench' },
  { id:'kids', name:'Anne & Bebek', icon:'fa-baby' },
  { id:'other', name:'Diğer', icon:'fa-boxes-stacked' }
];

const CATEGORY_ICON_POOL = ['fa-mobile-screen','fa-laptop','fa-car','fa-house','fa-couch','fa-wrench','fa-boxes-stacked','fa-shirt','fa-baby','fa-utensils','fa-book','fa-futbol','fa-gamepad','fa-tractor','fa-truck','fa-gem','fa-paw','fa-seedling','fa-motorcycle','fa-camera','fa-tv','fa-blender','fa-chair','fa-hammer','fa-paint-roller','fa-plug','fa-scissors','fa-briefcase','fa-bicycle','fa-ring'];
let users = [];
let archivedUsers = [];
let combos = [];
let ads = [];
let paymentSearchQuery = '';
let suppressPop = false;
let userCurrentCoords = null;
let activeRadiusKm = 0;
let currentDiscountTargetAd = null;

/* ================= INSTAGRAM SVG ICONS ================= */
const IGSVG = {
  home: f => f ? '<svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M3 10.2 12 2.6l9 7.6V22h-6.4v-6.2a2.6 2.6 0 0 0-5.2 0V22H3Z"/></svg>' : '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"><path d="M3 10.2 12 2.6l9 7.6V22h-6.4v-6.2a2.6 2.6 0 0 0-5.2 0V22H3Z"/></svg>',
  store: f => f ? '<svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M4.2 5.5 3 9.3c0 1.4 1 2.6 2.4 2.9V21h13.2v-8.8c1.4-.3 2.4-1.5 2.4-2.9l-1.2-3.8c-.3-.9-1.1-1.5-2-1.5H6.2c-.9 0-1.7.6-2 1.5ZM8.4 13.7h7.2V21H8.4Zm2.1-9.5h3l.7 2.3h-4.4Z"/></svg>' : '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"><path d="M4.2 5.5 3 9.3c0 1.4 1 2.6 2.4 2.9V21h13.2v-8.8c1.4-.3 2.4-1.5 2.4-2.9l-1.2-3.8c-.3-.9-1.1-1.5-2-1.5H6.2c-.9 0-1.7.6-2 1.5Z"/><path d="M8.4 21v-7.3h7.2V21"/></svg>',
  plusSq: () => '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><rect x="3" y="3" width="18" height="18" rx="4"/><path d="M12 8v8M8 12h8"/></svg>',
  heart: f => f ? '<svg width="24" height="24" viewBox="0 0 24 24" fill="#ed4956"><path d="M16.792 3.904A4.989 4.989 0 0 1 21.5 9.122c0 3.072-2.652 4.959-5.197 7.222-2.512 2.243-3.865 3.469-4.303 3.752-.477-.309-2.143-1.823-4.303-3.752C5.141 14.072 2.5 12.167 2.5 9.122a4.989 4.989 0 0 1 4.708-5.218 4.21 4.21 0 0 1 3.675 1.941c.84 1.175.98 1.763 1.12 1.763s.278-.588 1.11-1.766a4.17 4.17 0 0 1 3.679-1.938Z"/></svg>' : '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"><path d="M16.792 3.904A4.989 4.989 0 0 1 21.5 9.122c0 3.072-2.652 4.959-5.197 7.222-2.512 2.243-3.865 3.469-4.303 3.752-.477-.309-2.143-1.823-4.303-3.752C5.141 14.072 2.5 12.167 2.5 9.122a4.989 4.989 0 0 1 4.708-5.218 4.21 4.21 0 0 1 3.675 1.941c.84 1.175.98 1.763 1.12 1.763s.278-.588 1.11-1.766a4.17 4.17 0 0 1 3.679-1.938Z"/></svg>',
  comment: () => '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"><path d="M20.656 17.008a9.993 9.993 0 1 0-3.59 3.615L22 22Z"/></svg>',
  send: () => '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"><path d="M22 3 9.218 10.083"/><path d="M11.698 20.334 22 3H2l7.218 7.083 2.48 10.251Z"/></svg>',
  bookmark: f => f ? '<svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M20 21 12 13.44 4 21V3h16Z"/></svg>' : '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"><path d="M20 21 12 13.44 4 21V3h16Z"/></svg>',
  chevL: () => '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><path d="m15 6-6 6 6 6"/></svg>',
  chevR: () => '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"><path d="m9 6 6 6-6 6"/></svg>',
  search: () => '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="11" cy="11" r="7"/><path d="m20.5 20.5-4.2-4.2"/></svg>',
  moon: () => '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"><path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8Z"/></svg>',
  sun: () => '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>',
  verified: () => '<svg width="14" height="14" viewBox="0 0 24 24" class="inline-block"><path fill="#0095f6" d="M12 1.8l2.5 2.4 3.4-.6.6 3.4 3.1 1.5-1.5 3.1 1.5 3.1-3.1 1.5-.6 3.4-3.4-.6-2.5 2.4-2.5-2.4-3.4.6-.6-3.4-3.1-1.5 1.5-3.1-1.5-3.1 3.1-1.5.6-3.4 3.4.6Z"/><path fill="none" stroke="#fff" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" d="m8.6 12.2 2.3 2.3 4.3-5"/></svg>',
  star: f => f ? '<svg width="24" height="24" viewBox="0 0 24 24" fill="#f59e0b"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>' : '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>'
};

/* ================= BASIC HELPERS ================= */
const byId = id => document.getElementById(id);
const _0xSCAdmin = () => !!(currentUser && currentUser.role === 'SUPERUSER');
const _0xSCAmount = value => { const n = Number(value); return Number.isFinite(n) && n >= 0 ? Math.round(n * 100) / 100 : 0; };
const _0xSCCode = () => 'SHAM-' + Math.random().toString(36).slice(2, 8).toUpperCase() + '-' + Date.now().toString(36).toUpperCase().slice(-4);
const _0xSCBalance = uid => { const u = users.find(x => x.uid === uid) || (currentUser && currentUser.uid === uid ? currentUser : null); return Number(u?.avitocashBalance ?? u?.shamcashBalance ?? 0); };
const _0xGiftCode = () => 'GIFT-' + Math.random().toString(36).slice(2, 7).toUpperCase() + '-' + Date.now().toString(36).slice(-5).toUpperCase();
const _0xSCPrices = () => ({ adPrice: _0xSCAmount(AVITOCASH_PRICES.adPrice), shopSubscription: _0xSCAmount(AVITOCASH_PRICES.shopSubscription), editPrice: _0xSCAmount(AVITOCASH_PRICES.editPrice) });

/* ================= LOCALIZATION DICTIONARY ================= */
let currentLang = localStorage.getItem('bs_app_lang') || 'ru';
const TRANSLATE_CACHE = {};

const DICTIONARY = {
  'Главная': 'Ana Sayfa',
  'Магазины': 'Mağazalar',
  'Создать': 'İlan Ver',
  'Избранное': 'Favoriler',
  'Профиль': 'Profilim',
  'Техподдержка': 'Destek',
  'Поддержать проект': 'Projeyi Destekle',
  'Сменить тему': 'Temayı Değiştir',
  'Поиск': 'Arama...',
  'Светлая ☀️': 'Gündüz ☀️',
  'Темная 🌙': 'Gece 🌙',
  'Все регионы (Турция)': 'Tüm İller (Türkiye)',
  'Все регионы': 'Tüm İller',
  'Стамбул': 'İstanbul',
  'Анкара': 'Ankara',
  'Измир': 'İzmir',
  'Бурса': 'Bursa',
  'Анталья': 'Antalya',
  'Газиантеп': 'Gaziantep',
  'Хатай': 'Hatay',
  'Мерсин': 'Mersin',
  'Шанлыурфа': 'Şanlıurfa',
  'Конья': 'Konya',
  'Адана': 'Adana',
  'Кайсери': 'Kayseri',
  'Самсун': 'Samsun',
  'Трабзон': 'Trabzon',
  'Пожаловаться на объявление': 'İlanı Şikayet Et',
  'Мы проверим это объявление на нарушение правил.': 'Bu ilanı kurallara uygunluk açısından inceleyeceğiz.',
  'Выберите причину...': 'Sebep seçin...',
  'Мошенничество / Скам': 'Dolandırıcılık / Sahtekarlık',
  'Фейковый товар / Фото': 'Sahte Ürün / Yanıltıcı Fotoğraf',
  'Запрещенный товар': 'Yasaklı Ürün',
  'Спам / Дубликат': 'Spam / Tekrarlanan İlan',
  'Другое': 'Diğer',
  'Комментарий (необязательно)': 'Açıklama (isteğe bağlı)',
  'Отправить жалобу': 'Şikayeti Gönder',
  'Правила и рекомендации Авито Шам': 'Avita Turk Kullanım Kuralları',
  'Я подтверждаю и принимаю условия': 'Şartları Kabul Ediyorum',
  'Синхронизация с облаком…': 'Bulutla senkronize ediliyor…',
  'Язык переключен на русский': 'Dil Rusça olarak değiştirildi',
  'Язык переключен на турецкий': 'Dil Türkçe olarak değiştirildi',
  'Загрузка фото...': 'Fotoğraflar yükleniyor...',
  'Условия приняты. Добро пожаловать!': 'Şartlar kabul edildi. Hoş geldiniz!',
  'Ссылка скопирована!': 'Bağlantı kopyalandı!',
  'Удалено из избранного': 'Favorilerden kaldırıldı',
  'Добавлено в избранное!': 'Favorilere eklendi!',
  'Вы успешно заняли очередь!': 'Sıraya başarıyla girdiniz!',
  'Вы вышли из очереди': 'Sıradan çıktınız',
  'Вы вышли из аккаунта': 'Çıkış yapıldı',
  'Объявление опубликовано!': 'İlan başarıyla yayınlandı!',
  'Объявление обновлено!': 'İlan güncellendi!',
  'Объявление в архиве': 'İlan arşive kaldırıldı',
  'Объявление удалено': 'İlan silindi',
  'Жалоба отправлена. Спасибо!': 'Şikayetiniz iletildi. Teşekkür ederiz!',
  'Черновик удален': 'Taslak silindi',
  'Заполненность магазина': 'Mağaza İlan Kapasitesi',
  'Осталось мест': 'Kalan yer',
  'Лимит исчерпан': 'Limit doldu',
  'Расширить лимит (+50 мест / 5 AC)': 'Limiti Artır (+50 İlan / 5 AC)',
  'Лимит магазина успешно увеличен!': 'Mağaza limiti başarıyla artırıldı!',
  'Срок публикации истек': 'İlan süresi doldu',
  'Истек срок': 'Süresi Dolmuş',
  'Продлить бесплатно': 'Ücretsiz Yenile',
  'Продлить на 30 дней': '30 Gün Uzat',
  'Объявление успешно продлено и поднято в топ!': 'İlan başarıyla uzatıldı ve öne çıkarıldı!',
  'У вас есть объявления с истекшим сроком:': 'Süresi dolmuş ilanlarınız var:',
  'Дата публикации:': 'Yayın Tarihi:',
  'Действует до:': 'Bitiş Tarihi:',
  'Неактуально • Возможно, продано': 'Güncel Değil • Satılmış Olabilir',
  'Объявление не обновлялось более 30 дней. Товар может быть уже продан.': 'İlan 30 günden uzun süredir güncellenmedi. Satılmış olabilir.',
  'Объявлений пока нет. Будьте первым!': 'Henüz ilan yok. İlk ilanı siz verin!',
  'Авито Шам © 2026': 'Avita Turk © 2026',
'Активных объявл.': 'Aktif İlanlar',
'Магазинов': 'Mağazalar',
'Пользователей': 'Kullanıcılar',
'В архиве': 'Arşivde',
'Жалоб': 'Şikayetler',
'Категорий': 'Kategoriler',
'Курсов': 'Kurlar',
'Бегущая строка': 'Kayan Yazı',
'Бэкап БД': 'Veritabanı Yedeği',
'Актуальный финансовый отчет': 'Güncel Finansal Rapor',
'Обновлено:': 'Güncelleme:',
'Баланс пользователей': 'Kullanıcı Bakiyeleri',
'С балансом': 'Bakiyesi Olanlar',
'Ожидают проверки': 'İnceleme Bekliyor',
'заявок': 'başvuru',
'Подтверждено': 'Onaylandı',
'Отклонено заявок:': 'Reddedilen Başvurular:',
'Бэкапов пока нет.': 'Henüz yedekleme yok.',
'Скачать': 'İndir',
'Удалить': 'Sil',
'В комплекте: ': 'Paket İçeriği: ',
'Экономия:': 'Tasarruf:',
'КОМБО': 'KOMBO',
'товаров': 'ürün',
'Товар + Подарок': 'Ürün + Hediye',
'+Подарок': '+Hediye',
'Аукцион': 'Açık Artırma',
'В топ': 'Öne Çıkar',
'Скидка': 'İndirim',
'В комбо': 'Komboya Ekle',
'Изменить': 'Düzenle',
'Продано': 'Satıldı',
'Передумал': 'Vazgeçtim',
'В архив': 'Arşive Kaldır',
'Редактировать': 'Düzenle',
'Поделиться': 'Paylaş',
'Пожаловаться': 'Şikayet Et',
'Лайк': 'Beğen',
'Лайк поставлен': 'Beğenildi',
'Рейтинг:': 'Puan:',
'ГОРЯЧЕЕ ПРЕДЛОЖЕНИЕ!': 'GÜNÜN FIRSATI!',
'Специальная цена со скидкой': 'İndirimli Özel Fiyat',
'Предложить цену ($)': 'Fiyat Teklif Et ($)',
'Торг': 'Pazarlık',
'Дата публикации:': 'Yayın Tarihi:',
'Действует до:': 'Bitiş Tarihi:',
'Неактуально • Возможно, продано': 'Güncel Değil • Satılmış Olabilir',
'Объявление не обновлялось более 30 дней. Товар может быть уже продан.': 'İlan 30 günden uzun süredir güncellenmedi. Satılmış olabilir.',
'Описание и изъяны': 'Açıklama ve Kusurlar',
'Связаться через WhatsApp': 'WhatsApp ile İletişim',
'В очереди:': 'Sırada:',
'чел.': 'kişi',
'Вы №': 'Sıranız: No ',
'в очереди': 'sırada',
'Занять очередь': 'Sıraya Gir',
'Выйти из очереди': 'Sıradan Çık',
'Посмотреть очередь': 'Sırayı Gör',
'Очередь свободна': 'Sırada kimse yok',
'Будьте первым в очереди': 'İlk sırayı siz alın',
'Вы в очереди': 'Sıradaki yeriniz alındı',
  'Разработчик:': 'Geliştirici:',
  'Выберите регион': 'İl Seçiniz',
  'Подтверждение действия': 'İşlemi Onayla',
  'Подтвердите действие': 'İşlemi Onayla',
  'Да, выполнить': 'Tamam',
  'Отмена': 'İptal',
  'объявлений': 'ilan',
  'Объявлений': 'İlanlar',
  'Объявления': 'İlanlar',
  'Закрыть': 'Kapat',
  'Отмена': 'İptal',
  'Назад': 'Geri',
  'Вход': 'Giriş Yap',
  'Регистрация': 'Kayıt Ol',
  'Логин *': 'Kullanıcı Adı *',
  'Пароль *': 'Şifre *',
  'Имя / Кунья *': 'İsim / Lakap *',
  'Мужчина': 'Erkek',
  'Женщина 🌸': 'Kadın 🌸',
  'WhatsApp номер * (+90…)': 'WhatsApp Numarası * (+90…)',
  'Выберите ваш пол *': 'Cinsiyetinizi Seçin *',
  'Получить код': 'Kod Al',
  'Запомнить мой вход на этом устройстве': 'Beni bu cihazda hatırla',
'Код отправлен в WhatsApp': 'Kod WhatsApp\'a gönderildi',
'Отправить код повторно': 'Kodu tekrar gönder',
  'Войти': 'Giriş Yap',
  'Зарегистрироваться': 'Kayıt Ol',
  'Подача нового объявления': 'Yeni İlan Ver',
  'Заголовок объявления *': 'İlan Başlığı *',
  'Категория *': 'Kategori *',
  'Регион *': 'İl / Bölge *',
  'Только для женщин 🌸': 'Sadece Kadınlara Özel 🌸',
  'Город / Населенный пункт *': 'İlçe / Mahalle *',
  'Местоположение на карте *': 'Haritada Konum *',
  '(кликните на карту)': '(konumu seçmek için haritaya tıklayın)',
  'Отдать даром (Бесплатно) 🎁': 'Ücretsiz (Hediye) 🎁',
  'Безвозмездно нуждающимся': 'İhtiyaç sahiplerine ücretsiz',
  'Цена договорная 🤝': 'Fiyat Pazarlıklı 🤝',
  'Покупатели смогут предложить свою цену': 'Alıcılar kendi fiyat tekliflerini yapabilir',
  'Цена *': 'Fiyat *',
  'Фотографии товара (до 6 шт.) *': 'Ürün Fotoğrafları (en fazla 6 adet) *',
  'Выбрать фотографии': 'Fotoğraf Seç',
  'Ваше местоположение': 'Belirlenen Konumunuz',
  'Загрузить фото': 'Fotoğraf Yükle',
  'Описание и возможные изъяны *': 'Açıklama ve Varsa Kusurları *',
  'Опубликовать объявление': 'İlanı Yayınla',
  'Сохранить изменения': 'Değişiklikleri Kaydet',
  'Редактирование объявления': 'İlanı Düzenle',
  'ГЛАВНАЯ': 'ANA',
  'Рядом': 'Yakınımda',
  'Рядом со мной': 'Yakınımda',
  'Радиус поиска:': 'Arama Yarıçapı:',
  'км': 'km',
  'км от вас': 'km mesafede',
  'Отключить поиск рядом': 'Yakınımda aramasını kapat',
  'Геолокация недоступна': 'Konum alınamadı',
  'Поиск в радиусе': 'Yarıçap içinde ara',
  'Все расстояния': 'Tüm mesafeler',
  'Новые': 'En Yeniler',
  'Дешевые': 'En Ucuzlar',
  'Дорогие': 'En Pahalılar',
  'Популярные': 'Popülerler',
  'Сортировать по:': 'Sıralama:',
  '🕒 Сначала новые': '🕒 Önce En Yeniler',
  '💰 Сначала дешевые': '💰 Önce En Ucuzlar',
  '💎 Сначала дорогие': '💎 Önce En Pahalılar',
  '🔥 Популярные': '🔥 En Popülerler',
  'Все': 'Tümü',
  'Для женщин 🌸': 'Kadınlara Özel 🌸',
  'Женские объявления 🌸': 'Kadın İlanları 🌸',
  'Даром 🎁': 'Ücretsiz 🎁',
  'Скидки': 'İndirimler',
  'Акции': 'Kampanyalar',
'Электроника': 'Elektronik',
  'Транспорт': 'Vasıta & Araçlar',
  'Недвижимость': 'Emlak',
  'Инструменты': 'Alet & Edavat',
  'Для дома': 'Ev & Yaşam',
  'Продукты': 'Gıda & Market',
  'Питание': 'Gıda & Market',
  'Одежда': 'Giyim & Moda',
  'Одежда и мода': 'Giyim & Moda',
  'Детские товары': 'Anne & Bebek',
  'Услуги': 'Hizmetler',
  'Ремонт': 'Tamirat & Servis',
  'Прочее': 'Diğer',
  'Elektronik': 'Elektronik',
  'Vasıta & Araçlar': 'Vasıta & Araçlar',
  'Emlak': 'Emlak',
  'Alet & Edavat': 'Alet & Edavat',
  'Ev & Yaşam': 'Ev & Yaşam',
  'Gıda & Market': 'Gıda & Market',
  'Giyim & Moda': 'Giyim & Moda',
  'Hizmetler': 'Hizmetler',
  'Anne & Bebek': 'Anne & Bebek',
  'Diğer': 'Diğer',
  'Страница': 'Sayfa',
  'из': '/',
  '« Первая': '« İlk',
  '< Назад': '< Geri',
  'Вперед >': 'İleri >',
  'Последняя »': 'Son »',
  'объявл.': 'ilan',
  'лайков': 'beğeni',
  'просмотров': 'görüntülenme',
  'только что': 'az önce',
  'мин': 'dk',
  'ч': 'sa',
  'дн': 'gün',
  '🤝 Договорная': '🤝 Pazarlıklı',
  '🎁 ДАРОМ': '🎁 ÜCRETSİZ',
  'АКЦИЯ': 'KAMPANYA',
  'Нравится:': 'Beğeniler:',
  'Будьте первым, кому понравилось': 'İlk beğenen siz olun',
  '… ещё': '… devamı',
  'Куплено': 'Satın Alındı',
  'Продано': 'Satıldı',
  'Покупка': 'Satın Alma',
  'Получено': 'Alındı',
  'Отправлено': 'Gönderildi',
  'Пополнение': 'Bakiye Yükleme',
  'Подарок': 'Hediye',
  'Оплата услуги': 'Hizmet Ödemesi',
  'Взыскание': 'Kesinti',
  'Транзакция': 'İşlem',
  'Чеков пока нет — история покупок и продаж появится здесь': 'Henüz işlem geçmişi yok',
  'Баланс AvitoCash': 'AvitaCash Bakiyesi',
  'Пополнить': 'Yükle',
  'Код': 'Hediye Kodu',
  'Перевод': 'Transfer',
  'Тема экрана': 'Tema',
'Магазин': 'Mağaza',
  'Новая цена ($)': 'Yeni Fiyat ($)',
  'Срок действия': 'Süre',
  'Бессрочно': 'Süresiz',
  '24 часа (Скидка дня)': '24 Saat (Günün Fırsatı)',
  '3 дня (Выходные)': '3 Gün (Hafta Sonu)',
  '7 дней (Неделя скидок)': '7 Gün (İndirim Haftası)',
  'Применить скидку': 'İndirimi Uygula',
  'Отменить скидку (вернуть старую цену)': 'İndirimi Kaldır (Eski Fiyata Dön)',
  'Открыть': 'Mağaza Aç',
  'Смотреть магазин': 'Mağazayı Gör',
  'акций': 'kampanya',
  'акции': 'kampanya',
  'Подтвержденных магазинов в данном регионе пока нет.': 'Bu bölgede henüz onaylı mağaza bulunmamaktadır.',
  'Текущая цена:': 'Mevcut Fiyat:',
  'Установить скидку / Акцию': 'İndirim Uygula / Kampanya',
  'Новая цена ($)': 'Yeni Fiyat ($)',
  'Срок действия': 'Süre',
  'Бессрочно': 'Süresiz',
  '24 часа (Скидка дня)': '24 Saat (Günün Fırsatı)',
  '3 дня (Выходные)': '3 Gün (Hafta Sonu)',
  '7 дней (Неделя скидок)': '7 Gün (İndirim Haftası)',
  'Применить скидку': 'İndirimi Uygula',
  'Отменить скидку (вернуть старую цену)': 'İndirimi Kaldır (Eski Fiyata Dön)',
  'İndirim Uygula / Kampanya': 'İndirim Uygula / Kampanya',
  'İndirimi Uygula': 'İndirimi Uygula',
  'İndirimi Kaldır (Eski Fiyata Dön)': 'İndirimi Kaldır (Eski Fiyata Dön)',
  'Yeni Kampanya (Kombo Paket)': 'Yeni Kampanya (Kombo Paket)',
  'Kampanyayı Kaydet': 'Kampanyayı Kaydet',
  'Редактирование акции': 'Kampanyayı Düzenle',
  'Новая акция': 'Yeni Kampanya',
  'Название акции (напр.: Комплект солнечной энергетики)': 'Kampanya Başlığı (örn: Güneş Enerjisi Seti)',
  'Специальная цена комплекта, $ *': 'Özel Paket Fiyatı, $ *',
  'Товары в комплекте (минимум 2) *': 'Paket İçeriğindeki Ürünler (en az 2 adet) *',
  'Сохранить акцию': 'Kampanyayı Kaydet',
  'Новая акция': 'Yeni Kampanya',
  'У магазина пока нет активных товаров': 'Mağazanın henüz aktif ürünü yok',
  'Выберите минимум 2 товара для создания комбо. Выбрано:': 'Kombo oluşturmak için en az 2 ürün seçin. Seçilen:',
  'Товаров в комплекте:': 'Paketteki Ürün Sayısı:',
  'нет скидки': 'indirim yok',
  'Расширенные настройки': 'Gelişmiş Ayarlar',
  'Цена, $ *': 'Fiyat, $ *',
  'Связаться': 'İletişime Geç',
  'Настройки': 'Ayarlar',
  'Управление магазином': 'Mağaza Yönetimi',
  'Полная панель': 'Tüm Panel',
  'Бэкап (JSON)': 'Yedekle (JSON)',
  'Акции магазина:': 'Mağaza Kampanyaları:',
  'товаров в комплекте': 'ürün pakette',
  'Все товары': 'Tüm Ürünler',
  'Товаров пока нет': 'Henüz ürün bulunmamaktadır',
  'Магазин не найден': 'Mağaza bulunamadı',
  'Вид ленты объявлений': 'Görünüm Modu',
  'Сетка': 'Izgara',
  'Список': 'Liste',
  'Лента': 'Akış',
  'История сделок (чеки)': 'İşlem Geçmişi ve Makbuzlar',
'Панель Администратора': 'Yönetici Paneli',
  'Панель управления магазином': 'Mağaza Yönetim Paneli',
  'Подтвержден': 'Onaylı',
  'На проверке': 'İnceleniyor',
  'Редактировать магазин': 'Mağazayı Düzenle',
  'Создать комбо': 'Kombo Paket Oluştur',
  'Скидки витрины': 'Vitrin İndirimleri',
  'Добавить товар': 'Ürün Ekle',
  'Мои акции': 'Kampanyalarım',
  'Цена акции:': 'Kampanya Fiyatı:',
  'Личные категории магазина': 'Mağaza Özel Kategorileri',
  'Например: Запчасти или Чехлы': 'Örnek: Yedek Parça veya Kılıf',
  'Добавить': 'Ekle',
  'Собственных категорий пока нет': 'Henüz özel kategori eklenmedi',
  'Бэкап магазина (JSON)': 'Mağaza Yedeği (JSON)',
  'Экспорт': 'Dışa Aktar',
  'Импорт': 'İçe Aktar',
  'Товары Вашего магазина:': 'Mağazanızın Ürünleri:',
  'Товаров пока нет — нажмите «Добавить товар»': 'Henüz ürün yok — «Ürün Ekle» butonuna tıklayın',
  '+Подарок': '+Hediye',
  'Товар + Подарок': 'Ürün + Hediye',
  'Изменить анкету': 'Profili Düzenle',
  'Выйти': 'Çıkış Yap',
  'В очереди:': 'Sırada:',
  'чел.': 'kişi',
  'Вы №': 'Sıranız: No ',
  'в очереди': 'sırada',
  'Занять очередь': 'Sıraya Gir',
  'Выйти из очереди': 'Sıradan Çık',
  'Посмотреть очередь': 'Sırayı Gör',
  'Очередь свободна': 'Sırada kimse yok',
  'Будьте первым в очереди': 'İlk sırayı siz alın',
  'Вы в очереди': 'Sıradaki yeriniz alındı',
  'Описание и изъяны': 'Açıklama ve Kusurlar',
  'ОПИСАНИЕ И ИЗЪЯНЫ': 'AÇIKLAMA VE KUSURLAR',
  'Связаться через WhatsApp': 'WhatsApp ile İletişim',
  'Оплатить из баланса': 'Bakiyeden Öde',
  'Пожаловаться': 'Şikayet Et',
  'Передумал': 'Vazgeçtim',
  'Редактировать': 'Düzenle',
  'Изменить': 'Düzenle',
  'Скидка': 'İndirim',
  'В комбо': 'Komboya Ekle',
  'цена комплекта': 'paket fiyatı',
  'По отдельности:': 'Ayrı ayrı:',
  'выгода': 'kazanç',
  'Состав комбо-набора:': 'Paket İçeriği:',
  'Заказать комплект': 'Seti WhatsApp ile Sipariş Et',
  'Изменить акцию': 'Kampanyayı Düzenle',
  'Товары этой акции больше недоступны': 'Bu kampanyadaki ürünler artık mevcut değil',
  'Поделиться': 'Paylaş',
  'Аукцион': 'Açık Artırma',
  'В архив': 'Arşive Kaldır',
  'Рейтинг:': 'Puan:',
  'Лайк': 'Beğen',
  'Лайк поставлен': 'Beğenildi',
  'ГОРЯЧЕЕ ПРЕДЛОЖЕНИЕ!': 'GÜNÜN FIRSATI!',
  'Специальная цена со скидкой': 'İndirimli Özel Fiyat',
  'Экономия:': 'Kazanç:',
  'Торг': 'Pazarlık',
  'Предложить цену ($)': 'Fiyat Teklif Et ($)',
  'Подача объявления': 'Yeni İlan Ekle',
  'В топ': 'Öne Çıkar',
  '🚀 Объявление поднято на первое место в ленте!': '🚀 İlan başarıyla en üste çıkarıldı!'
};

function t(text) {
  if (!text || currentLang !== 'tr') return text;
  return DICTIONARY[text] || text;
}